---
# enforce ironic usage only with openvswitch
- include: ironic-check.yml

- include: register.yml
  when: inventory_hostname in groups['neutron-server']

- include: config.yml

- include: config-neutron-fake.yml
  when:
    - enable_nova_fake | bool
    - inventory_hostname in groups['compute']

- include: clone.yml
  when:
    - neutron_dev_mode | bool
    - inventory_hostname in groups['neutron-server'] or
      inventory_hostname in groups['neutron-dhcp-agent'] or
      inventory_hostname in groups['neutron-l3-agent'] or
      inventory_hostname in groups['neutron-lbaas-agent'] or
      inventory_hostname in groups['neutron-metadata-agent'] or
      inventory_hostname in groups['neutron-vpnaas-agent'] or
      inventory_hostname in groups['neutron-bgp-dragent']

- include: bootstrap.yml
  when: inventory_hostname in groups['neutron-server']

- name: Flush Handlers
  meta: flush_handlers
